{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: simgpu-grafana
type: Opaque
stringData:
  GRAFANA_URL: {{ .Values.grafana.url | quote }}
  GRAFANA_API_KEY: {{ .Values.grafana.apiKey | quote }}
  GRAFANA_REMOTE_WRITE_URL: {{ .Values.grafana.remoteWriteUrl | quote }}
  GRAFANA_PROM_USERNAME: {{ .Values.grafana.promUsername | quote }}
  GRAFANA_PROM_TOKEN: {{ .Values.grafana.promToken | quote }}
{{- end }}
