apiVersion: v1
kind: ServiceAccount
metadata:
  name: simgpu-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simgpu-api-job-launcher
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simgpu-api-job-launcher
subjects:
  - kind: ServiceAccount
    name: simgpu-api
roleRef:
  kind: Role
  name: simgpu-api-job-launcher
  apiGroup: rbac.authorization.k8s.io
